spring.application.name=wallet management system

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5431/wallet-management}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update


